### ISSUE TITLE
AndroidProgressBar is registered twice

### ISSUE THREAD

**Issue by soumyamishra89** [react-native-community/progress-bar-android#37]
# Bug

The AndroidProgressBar is registered with React Native core component. Hence it throws an error when used with the core component. 
`Invariant Violation: Tried to register two views with the same name AndroidProgressBar`

Rename the view used here as is done with the iOS progress view

**Comment by mauriciopf** [comment]
@Naturalclar quick question! Why didn't you use **createViewManagers** to register the manager instead of ** createNativeModules**??? example: [ReactSliderPackage](https://github.com/react-native-community/react-native-slider/blob/bc5589e3e19bf60ba7e8428ee940a6e532d02301/src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderPackage.java#L26). The reason why Im asking this is because it seems there's an error when trying to auto link the package.. it says that the RNCProgressBar cannot be found by the UIManager, cheers!

**Comment by Naturalclar** [comment]
@soumyamishra89 Released v1.0.2 with the fix included, thanks for opening up the issue!

@mauriciopf Thanks for the information and your PR! 
When I took over the package, it was already using createNativeModules and I didn't catch the mistake since it was working with NativeModules 😅

**Comment by fabiojiparana** [comment]
Olá boa noite,
Após instalação do pacote react-native-camera o meu começou a dar o erro `Invariant Violation: Tried to register two views with the same name AndroidProgressBar`. Já estou usando a versão "@react-native-community/progress-bar-android": "^1.0.2".

Alguma solução?
